dist: xenial 
language: python
python:
  - "3.7"
cache: pip
before_install:
  - sudo apt-get install libgdal-dev
install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -e . 
script: python3 studies/india_districts/india_Rt_est.py
branches:
  only:
  - master
