dist: xenial 
language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -e . 
script: python3 studies/india_districts/india_Rt_est.py --local
branches:
  only:
  - master
