name: run tutorial

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.9]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python setup.py install
      - name: install extra to run studies
        run: |
          python -m pip install tqdm
      - name: Run tutorial
        run: |
          cd docs/tutorial/ && python tutorial.py
